apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
        - name: stats
          image: us-central1-docker.pkg.dev/gke-flask-kubernetes/job-tracker/stats:v1
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
