apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: us-central1-docker.pkg.dev/gke-flask-kubernetes/job-tracker/tracker:v1
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: STATS_URL
              value: http://stats:5000
